<link href="uploader/css/jquery.dm-uploader.css" rel="stylesheet">
<link href="uploader/styles.css" rel="stylesheet">
<div class="mod_news_img">
    <script src="<?php echo WB_URL; ?>/modules/news_img/js/jquery.furl.js"></script>

    <h2><?php echo $TEXT['ADD'].'/'.$TEXT['MODIFY'].' '.$TEXT['POST']; ?></h2>
    <div class="jsadmin jcalendar hide"></div>
    <form name="modify" action="<?php echo WB_URL; ?>/modules/news_img/save_post.php" method="post" enctype="multipart/form-data">
    <?php echo $FTAN; ?>
    <input type="hidden" name="section_id" value="<?php echo $section_id; ?>" />
    <input type="hidden" name="page_id" value="<?php echo $page_id; ?>" />
    <input type="hidden" name="post_id" value="<?php echo $post_id; ?>" />
    <input type="hidden" name="savegoback" id="savegoback" value="" />

    <table>
        <tbody>
            <tr>
            	<td class="setting_name"><?php echo $TEXT['TITLE']; ?>:</td>
            	<td class="setting_value">
            		<input type="text" name="title" id="title<?php echo $page_id ?>" value="<?php echo(htmlspecialchars($fetch_content['title'])); ?>" maxlength="255" />
            	</td>
            </tr>
            <tr>
            	<td class="setting_name"><?php echo $MOD_NEWS_IMG['LINK']; ?>:</td>
            	<td class="setting_value">
            		<?php echo $linkbase ?>/<input type="text" name="link" id="link<?php echo $page_id ?>" value="<?php echo(htmlspecialchars($link)); ?>" maxlength="255" style="width:80%" /><?php echo PAGE_SPACER.$post_id.PAGE_EXTENSION ?>
            	</td>
            </tr>
            <tr>
            	<td class="setting_name"><?php echo $MOD_NEWS_IMG['PREVIEWIMAGE']; ?>:</td>
            	<td>
<?php if ($fetch_content['image'] != ""): ?>
                    <img class="img_list" style="float:left;margin-right:15px" src="<?php echo WB_URL.MEDIA_DIRECTORY ?>/.news_img/<?php echo $post_id.'/'.$fetch_content['image'] ?>" /> <?php echo $fetch_content['image'] ?><br />
                    <a href="<?php echo WB_URL ?>/modules/news_img/modify_post.php?page_id=<?php echo $page_id ?>&section_id=<?php echo $section_id ?>&post_id=<?php echo $post_id_key ?>&post_img=<?php echo $fetch_content['image'] ?>"><?php echo $TEXT['DELETE'] ?></a>
                    <input type="hidden" name="previewimage" value="<?php echo $fetch_content['image'] ?>" />
<?php else: ?>
                    <?php echo $MOD_NEWS_IMG['UPLOAD'] ?> <input type="file" name="postfoto" accept="image/*" />
<?php if(isset($allimg) && is_array($allimg) && count($allimg)>0): ?>
                    <?php echo $MOD_NEWS_IMG['OR'] ?>:
                    <select name="mediafile" id="mediafile">
                        <option value="" selected="selected"></option>
                    <?php foreach($allimg as $img): if(!array_key_exists($img['picname'],$seenimg)): ?>
                        <option value="<?php echo $img['id'] ?>"><?php echo $img['picname'] ?></option>
                    <?php endif; endforeach; ?>
                    </select><br />
<?php endif; endif; ?>
        		</td>
            </tr>
            <tr>
                <td class="setting_name"><?php echo $TEXT['GROUP']; ?>:</td>
                <td class="setting_value">
                    <select name="group">
                        <option value="<?php echo urlencode(serialize(array('g' => 0, 's' => $section_id, 'p' => $page_id))) ?>"><?php echo $TEXT['NONE']." (".$TEXT['CURRENT']." ".$TEXT['SECTION']." ".$section_id ?>)</option>
<?php if(isset($groups) && is_array($groups) && count($groups)>0): foreach($groups as $id => $group): ?>
                        <option value="<?php echo $id ?>"<?php if ($fetch_content['group_id'] == $group['group_id']): ?> selected="selected"<?php endif; ?>><?php echo $group['title'].' ('.$TEXT['CURRENT']." ".$TEXT['SECTION'].' '.$section_id ?>)</option>
<?php endforeach; endif; if(isset($groups_on_other_nwi_sections) && is_array($groups_on_other_nwi_sections) && count($groups_on_other_nwi_sections)>0): ?>
                        <option disabled value="0">[--- <?php echo $TEXT['PAGE'].' '.$pid.' ('.$page_title ?>) ---]</option>
<?php foreach($groups_on_other_nwi_sections as $id => $group): ?>
                        <option value="<?php echo $id ?>"><?php echo $group ?></option>
<?php endforeach; endif; ?>
                    </select>
                </td>
            </tr>
            <tr>
            	<td class="setting_name"><?php echo $TEXT['ACTIVE']; ?>:</td>
            	<td class="setting_value">
            		<input type="radio" name="active" id="active_true" value="1" <?php if ($fetch_content['active'] == 1): echo ' checked="checked"'; endif; ?> />
            		<a href="#" onclick="javascript: document.getElementById('active_true').checked = true;">
            		<?php echo $TEXT['YES']; ?>
            		</a>
            		&nbsp;
            		<input type="radio" name="active" id="active_false" value="0" <?php if ($fetch_content['active'] == 0): echo ' checked="checked"'; endif; ?> />
            		<a href="#" onclick="javascript: document.getElementById('active_false').checked = true;">
            		<?php echo $TEXT['NO']; ?>
            		</a>
            	</td>
            </tr>
            <tr>
            	<td class="setting_name"><?php echo $TEXT['PUBL_START_DATE']; ?>:</td>
            	<td class="setting_value">
            	   <input type="text" id="publishdate" name="publishdate" value="<?php if ($fetch_content['published_when']==0): print date($jscal_format, time()+TIMEZONE); else: print date($jscal_format, $fetch_content['published_when']+TIMEZONE); endif; ?>" style="width:33%;" />
                	<img src="<?php echo THEME_URL ?>/images/clock_16.png" id="publishdate_trigger" style="cursor: pointer;" title="<?php echo $TEXT['CALENDAR']; ?>" alt="<?php echo $TEXT['CALENDAR']; ?>" onmouseover="this.style.background='lightgrey';" onmouseout="this.style.background=''" />
                	<img src="<?php echo THEME_URL ?>/images/clock_del_16.png" style="cursor: pointer;" title="<?php echo $TEXT['DELETE_DATE']; ?>" alt="<?php echo $TEXT['DELETE_DATE']; ?>" onmouseover="this.style.background='lightgrey';" onmouseout="this.style.background=''" onclick="document.modify.publishdate.value=''" />
            	</td>
            </tr>
            <tr>
            	<td class="setting_name"><?php echo $TEXT['PUBL_END_DATE']; ?>:</td>
            	<td class="setting_value">
            	   <input type="text" id="enddate" name="enddate" value="<?php if ($fetch_content['published_until']!=0): print date($jscal_format, $fetch_content['published_until']+TIMEZONE); endif; ?>" style="width:33%;" />
                	<img src="<?php echo THEME_URL ?>/images/clock_16.png" id="enddate_trigger" style="cursor: pointer;" title="<?php echo $TEXT['CALENDAR']; ?>" alt="<?php echo $TEXT['CALENDAR']; ?>" onmouseover="this.style.background='lightgrey';" onmouseout="this.style.background=''" />
                	<img src="<?php echo THEME_URL ?>/images/clock_del_16.png" style="cursor: pointer;" title="<?php echo $TEXT['DELETE_DATE']; ?>" alt="<?php echo $TEXT['DELETE_DATE']; ?>" onmouseover="this.style.background='lightgrey';" onmouseout="this.style.background=''" onclick="document.modify.enddate.value=''" />
            	</td>
            </tr>
<?php if(isset($tags) && is_array($tags) && count($tags)>0): ?>
            <tr>
            	<td class="setting_name"><?php echo $MOD_NEWS_IMG['TAGS']; ?>:</td>
            	<td class="setting_value">
            		<div class="mod_news_img_taglist">
            		<?php foreach($tags as $t): ?>
                        <div class="mod_news_img_tag">
                            <input type="checkbox" name="tags[]" id="<?php echo $t['tag_id'] ?>" value="<?php echo $t['tag_id'] ?>"<?php if(array_key_exists($t['tag_id'],$assigned)): echo " checked='checked'"; endif; ?> />
                            <label class="mod_nwi_tag" for="<?php echo $t['tag_id'] ?>"><?php echo $t['tag'] ?></label>
                            <?php if($t['section_id']==0): ?>
                                <span class="fa fa-fw fa-star" title="<?php echo $MOD_NEWS_IMG['GLOBAL'] ?>"></span>
                            <?php endif; ?>
                        </div>
            		<?php endforeach; ?>
        			</div>
            	</td>
            </tr>
<?php endif; ?>
        </tbody>
    </table><hr />

    <table>
        <tbody>
        <tr>
        	<td valign="top"><?php echo $TEXT['SHORT']; ?>:</td>
        </tr>
        <tr>
        	<td>
        	<?php
            show_wysiwyg_editor("short", "short", htmlspecialchars($fetch_content['content_short']), "100%", "150px");
            ?>
        	</td>
        </tr>
        <tr>
        	<td valign="top"><?php echo $TEXT['LONG']; ?>:</td>
        </tr>
        <tr>
        	<td>
<?php
    show_wysiwyg_editor("long", "long", htmlspecialchars($fetch_content['content_long']), "100%", "350px");
?>
        	</td>
        </tr>
<?php if(NWI_USE_SECOND_BLOCK): ?>
        <tr>
        	<td valign="top"><?php echo $TEXT['BLOCK']; ?> 2:</td>
        </tr>
        <tr>
        	<td>
<?php
        show_wysiwyg_editor("block2", "block2", htmlspecialchars($fetch_content['content_block2']), "100%", "350px");
?>
        	</td>
        </tr>
<?php endif;?>
        </tbody>
    </table>

<?php ?>
    <div id="fotoshow"><a name="fs"></a>
    <h3><?php echo $MOD_NEWS_IMG['GALLERYIMAGES'] ?></h3>
    <table class="dragdrop_form">
        <tbody>
<?php if(isset($images) && is_array($images) && count($images)>0): $i=1; foreach($images as $image): ?>
            <tr id="img_id:<?php echo $image['id_key'] ?>">
	            <td class="dragdrop_item">&nbsp;</td>
                <td><?php echo $image['up'].$image['down'] ?></td>
                <td>
                    <a href="javascript:void(0);" onmouseover="XBT(this, {id:'tt<?php echo $i ?>'})">
                        <img class="img_list" src="<?php echo WB_URL.MEDIA_DIRECTORY ?>/.news_img/<?php echo $post_id ?>/thumb/<?php echo $image["picname"] ?>" />
                    </a>
                    <div id="tt<?php echo $i ?>" class="xbtooltip">
                        <img src="<?php echo WB_URL.MEDIA_DIRECTORY ?>/.news_img/<?php echo $post_id ?>/<?php echo $image["picname"] ?>" />
                    </div>
                </td>
                <td>
                    <?php echo $image["picname"] ?><br />
                    <input type="text" name="picdesc[<?php echo $image['id'] ?>]" value="<?php echo $image["picdesc"] ?>">
                </td>
                <td>
                    <a onclick="return confirm('<?php echo $MOD_NEWS_IMG['DELETEIMAGE'] ?>')" href="<?php echo WB_URL ?>/modules/news_img/modify_post.php?page_id=<?php echo $page_id ?>&section_id=<?php echo $section_id ?>&post_id=<?php echo $image['id_key'] ?>&img_id=<?php echo $image['id_key'] ?>#fs">
                        <img src="<?php echo THEME_URL ?>/images/delete_16.png" />
                    </a>
                </td>
                <td class="dragdrop_item">&nbsp;</td>
            </tr>
<?php $i++; endforeach; endif; ?>
        </tbody>
    </table>
