    <script src="<?php echo WB_URL; ?>/modules/news_img/js/datetimepickers/zebra/zebra_datepicker.min.js"></script>
    <script type="text/javascript">
        $(function() {
            $.fn.Zebra_DatePicker.defaults = {
                format: 'Y-m-d H:i',
                show_icon: false,
                enabled_minutes: 5
            };
            $('#publishdate').Zebra_DatePicker({
                
            });
            $('#enddate').Zebra_DatePicker({
                
            });
            $('#publishdate_trigger').click(function(){
                var datepicker = $('#publishdate').data('Zebra_DatePicker');
                datepicker.show();
            });
            $('#enddate_trigger').click(function(){
                var datepicker = $('#enddate').data('Zebra_DatePicker');
                datepicker.show();
            });
        });
    </script>